### ISSUE TITLE
Use go modules for dependency versioning

### ISSUE THREAD

**Issue by yoss22** [dblokhin/gringo#4]
Go now supports versioning dependencies using the go tool (https://github.com/golang/go/wiki/Modules). It might be worth using this so we don't accidentally depend on the wrong version of a dependency.

**Comment by dblokhin** [comment]
Yes, it's a good idea. The repo should go to use the latest golang dev features. Also I start tagging master with v0 tag that does not guarantee compatibilty with future releases.
